Traceback (most recent call last):
  File "/home/davide/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/davide/.local/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#> Show singular values and energy error
plt.figure()
plt.subplot(3,1,1)
plt.semilogy(s, 'o')
plt.title("Singular values")
plt.tight_layout()

energy = np.cumsum(s)
energy_error = np.sum(s) - np.cumsum(s)
plt.subplot(3,1,2)
plt.plot(energy/np.sum(s), 'o')
plt.title("Energy [%]")
plt.ylim(1e-2,1)
# plt.semilogy(energy_error/np.sum(s), 'o')
# plt.title("Energy error [%]")
# plt.ylim(1e-5,1)
plt.tight_layout()

storage = ( np.shape(image)[0] + np.shape(image)[1] ) * np.arange(len(s)) + np.arange(len(s))
storage_original = np.shape(image)[0] * np.shape(image)[1]
plt.subplot(3,1,3)
plt.plot(storage/original_data, label='compressed image')
plt.plot([0, len(s)-1], [1, 1], '--', label='original_data')
plt.title("Storage [% of the original image]")
plt.tight_layout()
plt.xlabel('$n_s$')

# plt.ylim(1e-5,1)
plt.show()



------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 22[0m
[1;32m     20[0m storage_original [38;5;241m=[39m np[38;5;241m.[39mshape(image)[[38;5;241m0[39m] [38;5;241m*[39m np[38;5;241m.[39mshape(image)[[38;5;241m1[39m]
[1;32m     21[0m plt[38;5;241m.[39msubplot([38;5;241m3[39m,[38;5;241m1[39m,[38;5;241m3[39m)
[0;32m---> 22[0m plt[38;5;241m.[39mplot(storage[38;5;241m/[39m[43moriginal_data[49m, label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcompressed image[39m[38;5;124m'[39m)
[1;32m     23[0m plt[38;5;241m.[39mplot([[38;5;241m0[39m, [38;5;28mlen[39m(s)[38;5;241m-[39m[38;5;241m1[39m], [[38;5;241m1[39m, [38;5;241m1[39m], [38;5;124m'[39m[38;5;124m--[39m[38;5;124m'[39m, label[38;5;241m=[39m[38;5;124m'[39m[38;5;124moriginal_data[39m[38;5;124m'[39m)
[1;32m     24[0m plt[38;5;241m.[39mtitle([38;5;124m"[39m[38;5;124mStorage [[39m[38;5;132;01m% o[39;00m[38;5;124mf the original image][39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'original_data' is not defined

